# permissions for end users to view k8snoviceoperators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: k8snoviceoperator-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: k8snovice-operator
    app.kubernetes.io/part-of: k8snovice-operator
    app.kubernetes.io/managed-by: kustomize
  name: k8snoviceoperator-viewer-role
rules:
- apiGroups:
  - k8snoviceoperator.jnytnai0613.github.io
  resources:
  - k8snoviceoperators
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - k8snoviceoperator.jnytnai0613.github.io
  resources:
  - k8snoviceoperators/status
  verbs:
  - get
