---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - k8snoviceoperator.jnytnai0613.github.io
  resources:
  - k8snoviceoperators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k8snoviceoperator.jnytnai0613.github.io
  resources:
  - k8snoviceoperators/finalizers
  verbs:
  - update
- apiGroups:
  - k8snoviceoperator.jnytnai0613.github.io
  resources:
  - k8snoviceoperators/status
  verbs:
  - get
  - patch
  - update
